config/routes.rb
SocialNetworkFinal::Application.routes.draw do
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  get "session/new"
  get "session/create"
  get "session/destroy"
  get "dashboard/index"
  get "home/index"
  get "static_page/home"
  get "static_page/help"
  get "static_page/contact"
  get "static_page/about"

  get "users/edit_password"

  resources :clients
  resources :sessions, only: [:new, :create, :destroy]

  resources :users

  root "home#index"

  match '/signup', to: 'users#new',         via: 'get'
  match '/signin', to: 'sessions#new',      via: 'get'
  match '/signout', to: 'sessions#destroy',  via: 'delete'

  namespace :admin do # stabilisce che a localhost:3000/admin indirizza a index dentro dashboard
    root "dashboard#index"
  end

end

app/models/client.rb
class Client < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase}
  #validations
  validates :name, presence: true, length:  {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format:  {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  #uniqueness -> unico  format per il formato presence per dire che deve essere presente
  validates :surname, presence: true, length: {maximum: 50} #aggiunto dopo la migration
  has_secure_password  #grazie alla gemma
  validates :password, length: {minimum: 6}


  #Con data_validator

  validates :birth, date: { before: Proc.new { Time.now - 3.year }, message: 'Troppo piccolo sei' }
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  layout 'admin' # per indicare il layout da caricare

  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def authorize
    if current_user.nil?
      flash[:danger] = "Not authorized"
      redirect_to signin_url
    end
    #redirect_to signin_url, danger: "Not authorized" if current_user.nil?
  end
  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render action: 'show', status: :created, location: @client }
      else
        format.html { render action: 'new' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :age)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @time=Time.now
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      #sign_in user
      session[:user_id] = user.id
      flash[:success] = "Welcome in Social Network 2014 #{user.name}"
      redirect_to user
    else
      flash[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:info] = 'Logged out'
    redirect_to root_url
  end

end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def home
    @time=Time.now
  end

  def help
  end

  def contact
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authorize, only: [:show]
  before_filter :authenticate_user!
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to(@user)
    else
      render "edit"
    end
  end

  def edit_password
    @user = User.find(current_user.id)
  end

  def update_password
    @user = User.find(current_user.id)
    if user.update_with_password(user_params)
      # Sign in the user by passing validation in case his password changed
      sign_in @user, :bypass => true
      redirect_to (@user)
    else
      render "edit_password"
    end
  end




  def destroy
    User.find(params[:id]).destroy
    session[:user_id] = nil
    flash[:info] = 'Destroy complete!'
    redirect_to root_url
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome in Social Network 2014! #{@user.name}"
      redirect_to @user
    else
      render 'new'
    end

    end


  private
  def user_params
    params.require(:user).permit(:name, :email, :surname, :birth, :password,
                                 :password_confirmation) # aggiunto surname
  end

end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "Ruby on Rails Social Network 2014"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/admin/dashboard/index.html.erb
<h1>Admin::Dashboard#index</h1>
<p>Find me in app/views/admin/dashboard/index.html.erb</p>

app/views/admin/shared/_header.html.erb
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/admin/shared/_menu.html.erb
<div class="navbar  navbar-default" role="navigation">
  <div class="container">
    <div class= "navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "DASHBOARD", admin_root_path, :class=> "navbar-brand" %>
    </div>
    <div class="navbar-collapse collapse">
      <form class="navbar-form navbar-right" role="form">
        <div class="form-group">
          <input type="text" placeholder="Email" class="form-control">
        </div>
        <div class="form-group">
          <input type="password" placeholder="Password" class="form-control">
        </div>
        <button type="submit" class="btn btn-primary">Sign in</button>
      </form>
      <ul class="nav  navbar-nav pull-right">
        <li><%= link_to "Home", root_path() %></li>
      </ul>
    </div>
  </div>
</div>

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<h1>Listing clients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td><%= client.age %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @client.age %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/home/index.html.erb
<%= provide(:title, "Home Page")%>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Social Network</title>
  <%= render :partial => "admin/shared/header" %> <!-- codice ruby per evitare di mettere 200 linee di codice in +
 si usa il partial per richiamare codice dal file header -->
</head>
<body>
<%= render :partial => "admin/shared/menu" %> <!-- per evitare di mettere 200 linee di codice in +
 si usa il partial per richiamare codice dal file header -->

<%= yield %> <!--indirizza tutti i file che abbiamo impostato permette di mettere il testo-->

</body>
</html>

app/views/layouts/application.html.erb
 <!-- codice ruby per evitare di mettere 200 linee di codice in +
 si usa il partial per richiamare codice dal file header -->
 <!-- per evitare di mettere 200 linee di codice in +
 si usa il partial per richiamare codice dal file header -->
<!--indirizza tutti i file che abbiamo impostato permette di mettere il testo-->

<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title))%> </title>
  <%= render :partial =>"shared/header"%>
</head>
<body>

<%= render :partial =>"shared/top_menu"%>

<div class="container">

  <%flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %>
        <a class="close" data-dismiss="alert">&#215;</a>
      </div>
  <% end %>

  <hr>
  <%= yield %>
  <hr>

  <%= debug(params) if Rails.env.development?%>
</div>

</body>
</html>

app/views/shared/_error_messages.html.erb
<%if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        <a class="close" data-dismiss="alert">&#215</a>
        The form contains <%= pluralize(object.errors.count, "error") %>.
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_header.html.erb
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/shared/_menu.html.erb
<div class="navbar  navbar-inverse" role="navigation">
  <div class="container">
    <div class= "navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "SOCIAL NETWORK", root_path, :class=> "navbar-brand" %>
    </div>
    <div class="navbar-collapse collapse">
      <form class="navbar-form navbar-right" role="form">
        <div class="form-group">
          <input type="text" placeholder="Email" class="form-control">
        </div>
        <div class="form-group">
          <input type="password" placeholder="Password" class="form-control">
        </div>
        <button type="submit" class="btn btn-primary">Sign in</button>
      </form>
      <ul class="nav  navbar-nav pull-right">
        <li><%= link_to "Home", root_path() %></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_top_menu.html.erb
<div class="navbar  navbar-inverse" role="navigation">
  <div class="container">
    <div class= "navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "SOCIAL NETWORK", root_path, :class=> "navbar-brand" %>
    </div>
    <div class="navbar-collapse collapse">

      <% if current_user %>
          <ul class="nav navbar-nav navbar-right">
            <li> <%= link_to current_user.email, user_path(current_user.id) %></li>
            <li><%= link_to "Log Out", session_path("current"), method: "delete" %></li>
          </ul>
      <% else %>
          <%= form_for(:session, url: sessions_path, :html =>{class: "navbar-form navbar-right"}) do |f| %>
              <div class="form-group">
                <%= f.text_field :email, class: "form-control", placeholder: "Email" %>
              </div>
              <div class="form-group">
                <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
              </div>
              <%= f.submit "Sign in", class: "btn btn-large btn-primary" %>
          <% end %>
      <% end %>
      <!--
        <form class="navbar-form navbar-right" role="form">
          <div class="form-group">
             <input type="text" placeholder="Email" class="form-control">
          </div>
          <div class="form-group">
             <input type="text" placeholder="Password" class="form-control">
          </div>
          <button type="submit" class="btn btn-primary">Sign in</button>
        </form>
        -->
    </div>
  </div>
</div>

app/views/static_page/about.html.erb
<h1>StaticPage#about</h1>
<p>Find me in app/views/static_page/about.html.erb</p>

app/views/static_page/contact.html.erb
<h1>ORA</h1>
<p>BASTA</p>

app/views/static_page/help.html.erb
<h1>StaticPage#help</h1>
<p>Find me in app/views/static_page/help.html.erb</p>

app/views/static_page/home.html.erb
<h1><%=@time%></h1>
<p>Find me in app/views/static_page/home.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <div class="form-group">
          <%= f.label :name, "Name" %>
          <%= f.text_field :name, :class=>"form-control", :placeholder =>"Name"%>
        </div>

        <div class="form-group">
          <!--<input type="date">-->
          <%= f.label :birth, "Birth" %> <br>
          <%= f.date_select :birth, :class=>"form-control", :placeholder =>"Birth"%>
        </div>

        <div class="form-group">
          <%= f.label :surname, "Surname" %>
          <%= f.text_field :surname, :class=>"form-control", :placeholder =>"Surname"%>
        </div>

        <div class="form-group">
          <%= f.label :email, "Email" %>
          <%= f.text_field :email, :class=>"form-control", :placeholder =>"Email"%>
        </div>

<!--
        <div class="form-group">
          <#%= f.label :password, "Password" %>
          <#%= f.password_field :password, :class=>"form-control", :placeholder =>"Password"%>
        </div>

        <div class="form-group">
          <#%= f.label :password_confirmation,"Password Confirmation" %>
          <#%= f.password_field :password_confirmation, class:"form-control", :placeholder =>"Password Confirmation"%>
        </div>
    -->    <br>
        <%= f.submit "Edit account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/edit_password.html.erb
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

                <div class="form-group">
                  <%= f.label :current_password, "Current Password" %> <i>(we need your current password to confirm your changes)</i><br>
                   <%= f.password_field :current_password, :class=>"form-control", :placeholder =>"Current Password"%>
                 </div>


                <div class="form-group">
                  <%= f.label :password, "New Password" %>
                  <%= f.password_field :password, :class=>"form-control", :placeholder =>"Password"%>
                </div>

                <div class="form-group">
                  <%= f.label :password_confirmation,"Password Confirmation" %>
                  <%= f.password_field :password_confirmation, class:"form-control", :placeholder =>"Password Confirmation"%>
                </div>
            <br>
        <%= f.submit "Edit password", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <div class="form-group">
          <%= f.label :name, "Name" %>
          <%= f.text_field :name, :class=>"form-control", :placeholder =>"Name"%>
        </div>

        <div class="form-group">
          <%= f.label :surname, "Surname" %>
          <%= f.text_field :surname, :class=>"form-control", :placeholder =>"Surname"%>
        </div>

        <div class="form-group">
          <!--<input type="date">-->
          <%= f.label :birth, "Birth" %> <br>
          <%= f.date_select :birth, :class=>"form-control", :placeholder =>"Birth"%>
        </div>

        <div class="form-group">
          <%= f.label :email, "Email" %>
          <%= f.text_field :email, :class=>"form-control", :placeholder =>"Email"%>
        </div>

        <div class="form-group">
          <%= f.label :password, "Password" %>
          <%= f.password_field :password, :class=>"form-control", :placeholder =>"Password"%>
        </div>

        <div class="form-group">
          <%= f.label :password_confirmation,"Password Confirmation" %>
          <%= f.password_field :password_confirmation, class:"form-control", :placeholder =>"Password Confirmation"%>
        </div>
        <br>
        <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= provide(:title, @user.name)%>  <!--definito in application helper-->
<div class="row">
  <div class ="col-md-3">
    <%= gravatar_for @user%><!-- metodo definito in users helpers-->
    <br>
    <%= @user.name%>
    <br>
    <%= @user.surname%>
    <br>
    <%= @user.email%>
    <br>
    <%= link_to 'Edit', edit_user_path%>
    <%= link_to 'Edit Password', users_edit_password_path%>
    <%= link_to 'Delete Account', @user, :method => :delete, data: {confirm: 'Are you sure?'} %>
    </div>
  <div class="col-md-9">
    <h1>My posts</h1>
  </div>
</div>